### PR TITLE
fix: don't set null/undefined HTTP headers

### LINKED ISSUE #52: HTTP client doesn't filter nulls/undefined in headers
# This is a Bug Report

## Description

* What went wrong?

In an integration test, where my function is called with `{}` as context, the HTTP client fails to make a request because `awsRequestId` was `undefined` and it tried to create a HTTP header with `undefined`.

* What did you expect should have happened?

Correlation IDs that are `undefined` or `null` should be skipped when we create the HTTP headers.

## Additional Data

* ***Which powertool package are you using?***: HTTP client
* ***Which version are you using?***: 1.5.1
* ***Middy engine version you're using***:
* ***Operating System***: OSX
* ***Stack Trace***:
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by theburningmonk**
## What did you implement:

Closes #52

## Todos:

- [x] Write tests
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

File: packages/lambda-powertools-http-client/index.js [hunk 1]
```diff
@@ -34,7 +34,10 @@ function getRequest (uri, method) {
 function setHeaders (request, headers) {
   const headerNames = Object.keys(headers)
   headerNames.forEach(h => {
-    request = request.set(h, headers[h])
+    const headerValue = headers[h]
+    if (headerValue) {
```
Comment (gsingh1) [inline packages/lambda-powertools-http-client/index.js]: This may be slightly safer in some instances... 
```suggestion
    if (!!headerValue) {
```
